-- Create the happy feet shoe store database

-- 40100 DEFAULT CHARACTER SET utf8mb4
DROP DATABASE IF EXISTS happyfeetshoestore;
CREATE DATABASE happyfeetshoestore;
USE happyfeetshoestore;

-- Create State Table
CREATE TABLE `state` (
 `stateCode` char(2) NOT NULL,
 `stateName` varchar(30) NOT NULL,
 PRIMARY KEY (`stateCode`)
); -- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

-- Create Country table
CREATE TABLE `country` (
 `countryCode` char(2) NOT NULL,
 `countryName` varchar(50) NOT NULL,
 PRIMARY KEY (`countryCode`)
); -- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

-- Create address table
CREATE TABLE `address` (
 `addressID` int(11) NOT NULL AUTO_INCREMENT,
 `street` varchar(50) NOT NULL,
 `city` varchar(30) NOT NULL,
 `stateCode` char(2) DEFAULT NULL,
 `countryCode` char(2) NOT NULL,
 `postalCode` varchar(20) NOT NULL,
 PRIMARY KEY (`addressID`),
 KEY `fk_stateCode` (`stateCode`),
 KEY `fk_countryCode` (`countryCode`),
 CONSTRAINT `fk_countryCode` FOREIGN KEY (`countryCode`) REFERENCES `country` (`countryCode`),
 CONSTRAINT `fk_stateCode` FOREIGN KEY (`stateCode`) REFERENCES `state` (`stateCode`)
); -- ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4

-- Create User table
CREATE TABLE `user` (
 `userID` int(11) NOT NULL AUTO_INCREMENT,
 `firstName` varchar(50) NOT NULL,
 `lastName` varchar(50) NOT NULL,
 `email` varchar(50) NOT NULL,
 `phone` varchar(20) DEFAULT NULL,
 `addressID` int(11) NOT NULL,
 `password` varchar(255) NOT NULL,
 PRIMARY KEY (`userID`),
 UNIQUE KEY `email` (`email`),
 KEY `fk_addressID` (`addressID`),
 CONSTRAINT `fk_addressID` FOREIGN KEY (`addressID`) REFERENCES `address` (`addressID`)
); -- ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4

-- Create Category table
CREATE TABLE `category` (
 `categoryID` int(11) NOT NULL AUTO_INCREMENT,
 `categoryName` varchar(20) NOT NULL,
 PRIMARY KEY (`categoryID`)
); -- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

-- Create Color table
CREATE TABLE `color` (
 `colorID` int(11) NOT NULL AUTO_INCREMENT,
 `colorName` varchar(20) NOT NULL,
 PRIMARY KEY (`colorID`)
); -- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

-- Create Product Table
CREATE TABLE `product` (
 `productID` int(11) NOT NULL AUTO_INCREMENT,
 `productName` varchar(50) NOT NULL,
 `section` varchar(20) NOT NULL,
 `categoryID` int(11) NOT NULL,
 `colorID` int(11) NOT NULL,
 `price` decimal(18,2) NOT NULL,
 PRIMARY KEY (`productID`),
 KEY `fk_categoryID` (`categoryID`),
 KEY `fk_colorID` (`colorID`),
 CONSTRAINT `fk_categoryID` FOREIGN KEY (`categoryID`) REFERENCES `category` (`categoryID`),
 CONSTRAINT `fk_colorID` FOREIGN KEY (`colorID`) REFERENCES `color` (`colorID`)
); -- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

-- Create Shoeorder table
CREATE TABLE `shoeorder` (
 `userID` int(11) NOT NULL,
 `productID` int(11) NOT NULL,
 `date` datetime NOT NULL,
 `addressID` int(11) NOT NULL,
 KEY `fk_userID` (`userID`),
 KEY `fk_productID` (`productID`),
 CONSTRAINT `fk_productID` FOREIGN KEY (`productID`) REFERENCES `product` (`productID`),
 CONSTRAINT `fk_userID` FOREIGN KEY (`userID`) REFERENCES `user` (`UserID`)
); -- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

-- Insert values into Country table
INSERT INTO country VALUES
('AF', 'Afghanistan'), 
('AX', 'Aland Islands'), 
('AL', 'Albania'), 
('DZ', 'Algeria'), 
('AS', 'American Samoa'), 
('AD', 'Andorra'), 
('AO', 'Angola'), 
('AI', 'Anguilla'), 
('AQ', 'Antarctica'), 
('AG', 'Antigua and Barbuda'), 
('AR', 'Argentina'), 
('AM', 'Armenia'), 
('AW', 'Aruba'), 
('AU', 'Australia'), 
('AT', 'Austria'), 
('AZ', 'Azerbaijan'), 
('BS', 'Bahamas, The'), 
('BH', 'Bahrain'), 
('BD', 'Bangladesh'), 
('BB', 'Barbados'), 
('BY', 'Belarus'), 
('BE', 'Belgium'), 
('BZ', 'Belize'), 
('BJ', 'Benin'), 
('BM', 'Bermuda'), 
('BT', 'Bhutan'), 
('BO', 'Bolivia'), 
('BA', 'Bosnia and Herzegovina'), 
('BW', 'Botswana'), 
('BV', 'Bouvet Island'), 
('BR', 'Brazil'), 
('IO', 'British Indian Ocean Territory'), 
('BN', 'Brunei Darussalam'), 
('BG', 'Bulgaria'), 
('BF', 'Burkina Faso'), 
('BI', 'Burundi'), 
('KH', 'Cambodia'), 
('CM', 'Cameroon'), 
('CA', 'Canada'), 
('CV', 'Cape Verde'), 
('KY', 'Cayman Islands'), 
('CF', 'Central African Republic'), 
('TD', 'Chad'), 
('CL', 'Chile'), 
('CN', 'China'), 
('CX', 'Christmas Island'), 
('CC', 'Cocos (Keeling) Islands'), 
('CO', 'Colombia'), 
('KM', 'Comoros'), 
('CG', 'Congo'), 
('CD', 'Congo, The Democratic Republic Of The'), 
('CK', 'Cook Islands'), 
('CR', 'Costa Rica'), 
('CI', 'Cote D''ivoire'), 
('HR', 'Croatia'), 
('CY', 'Cyprus'), 
('CZ', 'Czech Republic'), 
('DK', 'Denmark'), 
('DJ', 'Djibouti'), 
('DM', 'Dominica'), 
('DO', 'Dominican Republic'), 
('EC', 'Ecuador'), 
('EG', 'Egypt'), 
('SV', 'El Salvador'), 
('GQ', 'Equatorial Guinea'), 
('ER', 'Eritrea'), 
('EE', 'Estonia'), 
('ET', 'Ethiopia'), 
('FK', 'Falkland Islands - Malvinas'), 
('FO', 'Faroe Islands'), 
('FJ', 'Fiji'), 
('FI', 'Finland'), 
('FR', 'France'), 
('GF', 'French Guiana'), 
('PF', 'French Polynesia'), 
('TF', 'French Southern Territories'), 
('GA', 'Gabon'), 
('GM', 'Gambia, The'), 
('GE', 'Georgia'), 
('DE', 'Germany'), 
('GH', 'Ghana'), 
('GI', 'Gibraltar'), 
('GR', 'Greece'), 
('GL', 'Greenland'), 
('GD', 'Grenada'), 
('GP', 'Guadeloupe'), 
('GU', 'Guam'), 
('GT', 'Guatemala'), 
('GG', 'Guernsey'), 
('GN', 'Guinea'), 
('GW', 'Guinea-Bissau'), 
('GY', 'Guyana'), 
('HT', 'Haiti'), 
('HM', 'Heard Island and the McDonald Islands'), 
('VA', 'Holy See'), 
('HN', 'Honduras'), 
('HK', 'Hong Kong'), 
('HU', 'Hungary'), 
('IS', 'Iceland'), 
('IN', 'India'), 
('ID', 'Indonesia'), 
('IQ', 'Iraq'), 
('IE', 'Ireland'), 
('IM', 'Isle Of Man'),
('IT', 'Italy'), 
('JM', 'Jamaica'), 
('JP', 'Japan'), 
('JE', 'Jersey'), 
('JO', 'Jordan'), 
('KZ', 'Kazakhstan'), 
('KE', 'Kenya'), 
('KI', 'Kiribati'), 
('KR', 'Korea, Republic Of'), 
('KW', 'Kuwait'), 
('KG', 'Kyrgyzstan'), 
('LA', 'Lao People''s Democratic Republic'), 
('LV', 'Latvia'), 
('LB', 'Lebanon'), 
('LS', 'Lesotho'), 
('LR', 'Liberia'), 
('LY', 'Libya'), 
('LI', 'Liechtenstein'), 
('LT', 'Lithuania'), 
('LU', 'Luxembourg'), 
('MO', 'Macao'), 
('MK', 'Macedonia, The Former Yugoslav Republic Of'), 
('MG', 'Madagascar'), 
('MW', 'Malawi'), 
('MY', 'Malaysia'), 
('MV', 'Maldives'), 
('ML', 'Mali'), 
('MT', 'Malta'), 
('MH', 'Marshall Islands'), 
('MQ', 'Martinique'), 
('MR', 'Mauritania'), 
('MU', 'Mauritius'), 
('YT', 'Mayotte'), 
('MX', 'Mexico'), 
('FM', 'Micronesia, Federated States Of'), 
('MD', 'Moldova, Republic Of'), 
('MC', 'Monaco'), 
('MN', 'Mongolia'), 
('ME', 'Montenegro'), 
('MS', 'Montserrat'), 
('MA', 'Morocco'), 
('MZ', 'Mozambique'), 
('MM', 'Myanmar'), 
('NA', 'Namibia'), 
('NR', 'Nauru'), 
('NP', 'Nepal'), 
('NL', 'Netherlands'), 
('AN', 'Netherlands Antilles'), 
('NC', 'New Caledonia'), 
('NZ', 'New Zealand'), 
('NI', 'Nicaragua'), 
('NE', 'Niger'), 
('NG', 'Nigeria'), 
('NU', 'Niue'), 
('NF', 'Norfolk Island'), 
('MP', 'Northern Mariana Islands'), 
('NO', 'Norway'), 
('OM', 'Oman'), 
('PK', 'Pakistan'), 
('PW', 'Palau'), 
('PS', 'Palestinian Territories'), 
('PA', 'Panama'), 
('PG', 'Papua New Guinea'), 
('PY', 'Paraguay'), 
('PE', 'Peru'), 
('PH', 'Philippines'), 
('PN', 'Pitcairn'), 
('PL', 'Poland'), 
('PT', 'Portugal'), 
('PR', 'Puerto Rico'), 
('QA', 'Qatar'), 
('RE', 'Reunion'), 
('RO', 'Romania'), 
('RU', 'Russian Federation'), 
('RW', 'Rwanda'), 
('BL', 'Saint Barthelemy'), 
('SH', 'Saint Helena'), 
('KN', 'Saint Kitts and Nevis'), 
('LC', 'Saint Lucia'), 
('MF', 'Saint Martin'), 
('PM', 'Saint Pierre and Miquelon'), 
('VC', 'Saint Vincent and The Grenadines'), 
('WS', 'Samoa'), 
('SM', 'San Marino'), 
('ST', 'Sao Tome and Principe'), 
('SA', 'Saudi Arabia'), 
('SN', 'Senegal'), 
('RS', 'Serbia'), 
('SC', 'Seychelles'), 
('SL', 'Sierra Leone'), 
('SG', 'Singapore'), 
('SK', 'Slovakia'), 
('SI', 'Slovenia'), 
('SB', 'Solomon Islands'), 
('SO', 'Somalia'), 
('ZA', 'South Africa'), 
('GS', 'South Georgia and the South Sandwich Islands'), 
('ES', 'Spain'), 
('LK', 'Sri Lanka'), 
('SR', 'Suriname'), 
('SJ', 'Svalbard and Jan Mayen'), 
('SZ', 'Swaziland'), 
('SE', 'Sweden'), 
('CH', 'Switzerland'), 
('TW', 'Taiwan'), 
('TJ', 'Tajikistan'), 
('TZ', 'Tanzania, United Republic Of'), 
('TH', 'Thailand'), 
('TL', 'Timor-leste'), 
('TG', 'Togo'), 
('TK', 'Tokelau'), 
('TO', 'Tonga'), 
('TT', 'Trinidad and Tobago'), 
('TN', 'Tunisia'), 
('TR', 'Turkey'), 
('TM', 'Turkmenistan'), 
('TC', 'Turks and Caicos Islands'), 
('TV', 'Tuvalu'), 
('UG', 'Uganda'), 
('UA', 'Ukraine'), 
('AE', 'United Arab Emirates'), 
('GB', 'United Kingdom'), 
('US', 'United States'), 
('UM', 'United States Minor Outlying Islands'), 
('UY', 'Uruguay'), 
('UZ', 'Uzbekistan'), 
('VU', 'Vanuatu'), 
('VE', 'Venezuela'), 
('VN', 'Vietnam'), 
('VG', 'Virgin Islands, British'), 
('VI', 'Virgin Islands, U.S.'), 
('WF', 'Wallis and Futuna'), 
('EH', 'Western Sahara'), 
('YE', 'Yemen'), 
('ZM', 'Zambia'), 
('ZW', 'Zimbabwe');

-- Insert values into states values
INSERT INTO state VALUES
 ('AL' , 'Alabama'),
 ('AK' , 'Alaska'),
 ('AZ' , 'Arizona'),
 ('AR' , 'Arkansas'),
 ('CA' , 'California'),
 ('CO' , 'Colorado'),
 ('CT' , 'Connecticut'),
 ('DE' , 'Delaware'),
 ('FL' , 'Florida'),
 ('GA' , 'Georgia'),
 ('HI' , 'Hawaii'),
 ('ID' , 'Idaho'),
 ('IL' , 'Illinois'),
 ('IN' , 'Indiana'),
 ('IA' , 'Iowa'),
 ('KS' , 'Kansas'),
 ('KY' , 'Kentucky'),
 ('LA' , 'Louisiana'),
 ('ME' , 'Maine'),
 ('MD' , 'Maryland'),
 ('MA' , 'Massachusetts'),
 ('MI' , 'Michigan'),
 ('MN' , 'Minnesota'),
 ('MS' , 'Mississippi'),
 ('MO' , 'Missouri'),
 ('MT' , 'Montana'),
 ('NE' , 'Nebraska'),
 ('NV' , 'Nevada'),
 ('NH' , 'New Hampshire'),
 ('NJ' , 'New Jersey'),
 ('NM' , 'New Mexico'),
 ('NY' , 'New York'),
 ('NC' , 'North Carolina'),
 ('ND' , 'North Dakota'),
 ('OH' , 'Ohio'),
 ('OK' , 'Oklahoma'),
 ('OR' , 'Oregon'),
 ('PA' , 'Pennsylvania'),
 ('RI' , 'Rhode Island'),
 ('SC' , 'South Carolina'),
 ('SD' , 'South Dakota'),
 ('TN' , 'Tennessee'),
 ('TX' , 'Texas'),
 ('UT' , 'Utah'),
 ('VT' , 'Vermont'),
 ('VA' , 'Virginia'),
 ('WA' , 'Washington'),
 ('WV' , 'West Virginia'),
 ('WI' , 'Wisconsin'),
 ('WY' , 'Wyoming');

 -- Insert values into color table
INSERT INTO color (colorName) VALUES 
('black'),
('brown'),
('dark brown'),
('camel'),
('gray'),
('blue'),
('light blue'),
('green'),
('light green'),
('red'),
('maroon'),
('beige'),
('pink'),
('purple'),
('yellow'),
('orange'),
('checkers');

-- Insert values into category table
INSERT INTO category (categoryName) VALUES 
('boots'), ('casual'), ('formal'), ('slippers');

-- Insert values into products table
INSERT INTO product (productName, section, categoryID, colorID, price) VALUES
 ('Chelsea Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'black'), 52.5),
 ('Chelsea Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'brown'), 52.5),
 ('Chelsea Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'camel'), 52.5),
 ('Chelsea Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'gray'), 52.5),
 ('Leather Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'black'), 60.3),
 ('Leather Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'brown'), 60.3),
 ('Leather Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'camel'), 60.3),
 ('Leather Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'gray'), 60.3),
 ('Snow Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'black'), 48.8),
 ('Snow Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'blue'), 48.8),
 ('Snow Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'brown'), 48.8),
 ('Snow Boots','men', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'gray'), 48.8),
 ('Loafers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'black'), 35.8),
 ('Loafers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'blue'), 35.8),
 ('Loafers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'brown'), 35.8),
 ('Loafers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'green'), 35.8),
 ('Loafers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'red'), 35.8),
 ('Vans Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'black'), 45.2),
 ('Vans Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'blue'), 45.2),
 ('Vans Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'gray'), 45.2),
 ('Vans Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'green'), 45.2),
 ('Sports Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'black'), 57.4),
 ('Sports Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'blue'), 57.4),
 ('Sports Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'gray'), 57.4),
 ('Sports Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'green'), 57.4),
 ('Sports Sneakers','men', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'red'), 57.4),
 ('Brogues','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'black'), 64.5),
 ('Brogues','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'blue'), 64.5),
 ('Brogues','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'brown'), 64.5),
 ('Brogues','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'dark brown'), 64.5),
 ('Brogues','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'gray'), 64.5),
 ('Leather Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'black'), 55.0),
 ('Leather Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'blue'), 55.0),
 ('Leather Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'brown'), 55.0),
 ('Leather Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'gray'), 55.0),
 ('Leather Lace-up Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'black'), 57.9),
 ('Leather Lace-up Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'blue'), 57.9),
 ('Leather Lace-up Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'brown'), 57.9),
 ('Leather Lace-up Dress Shoes','men', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'gray'), 57.9),
 ('Flip-flops','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'blue'), 20.7),
 ('Flip-flops','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'gray'), 20.7),
 ('Flip-flops','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'green'), 20.7),
 ('Flip-flops','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'red'), 20.7),
 ('Leather Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'blue'), 26.3),
 ('Leather Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'brown'), 26.3),
 ('Leather Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'gray'), 26.3),
 ('Leather Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'dark brown'), 26.3),
 ('Winter Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'blue'), 25.4),
 ('Winter Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'beige'), 25.4),
 ('Winter Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'green'), 25.4),
 ('Winter Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'checkers'), 25.4),
 ('Winter Slippers','men', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'gray'), 25.4),
 ('Furry Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'black'), 61.8),
 ('Furry Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'blue'), 61.8),
 ('Furry Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'brown'), 61.8),
 ('Furry Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'gray'), 61.8),
 ('Furry Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'maroon'), 61.8),
 ('High Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'black'), 66.9),
 ('High Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'camel'), 66.9),
 ('High Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'brown'), 66.9),
 ('High Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'gray'), 66.9),
 ('High Leather Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'maroon'), 66.9),
 ('Low Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'black'), 38.2),
 ('Low Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'blue'), 38.2),
 ('Low Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'brown'), 38.2),
 ('Low Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'camel'), 38.2),
 ('Low Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'gray'), 38.2),
 ('Waterproof Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'blue'), 40.4),
 ('Waterproof Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'brown'), 40.4),
 ('Waterproof Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'gray'), 40.4),
 ('Waterproof Boots','women', (SELECT categoryID FROM category WHERE categoryName = 'boots'), (SELECT colorID FROM color WHERE colorName = 'maroon'), 40.4),
 ('Flower Sneakers','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'beige'), 30.5),
 ('Flower Sneakers','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'gray'), 30.5),
 ('Flower Sneakers','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'light blue'), 30.5),
 ('Flower Sneakers','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'light green'), 30.5),
 ('Sandals','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'beige'), 22.7),
 ('Sandals','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'blue'), 22.7),
 ('Sandals','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'pink'), 22.7),
 ('Sandals','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'purple'), 22.7),
 ('Slip-on Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'blue'), 25.8),
 ('Slip-on Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'green'), 25.8),
 ('Slip-on Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'gray'), 25.8),
 ('Slip-on Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'orange'), 25.8),
 ('Sports Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'black'), 39.3),
 ('Sports Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'blue'), 39.3),
 ('Sports Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'casual'), (SELECT colorID FROM color WHERE colorName = 'gray'), 39.3);

 -- Insert more shoes for women
  INSERT INTO product (productName, section, categoryID, colorID, price) VALUES
 ('Low Heel Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'black'), 27.7),
 ('Low Heel Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'blue'), 27.7),
 ('Low Heel Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'gray'), 27.7),
 ('Low Heel Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'brown'), 27.7),
 ('Metal Buckle Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'black'), 35.9),
 ('Metal Buckle Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'blue'), 35.9),
 ('Metal Buckle Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'brown'), 35.9),
 ('Metal Buckle Dress Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'green'), 35.9),
 ('Open Toe Heels','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'black'), 42.2),
 ('Open Toe Heels','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'blue'), 42.2),
 ('Open Toe Heels','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'light blue'), 42.2),
 ('Open Toe Heels','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'red'), 42.2),
 ('Ribbon Leather Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'black'), 58.3),
 ('Ribbon Leather Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'blue'), 58.3),
 ('Ribbon Leather Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'gray'), 58.3),
 ('Ribbon Leather Shoes','women', (SELECT categoryID FROM category WHERE categoryName = 'formal'), (SELECT colorID FROM color WHERE colorName = 'green'), 58.3),
 ('Flip-flops','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'red'), 19.4),
 ('Flip-flops','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'blue'), 19.4),
 ('Flip-flops','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'gray'), 19.4),
 ('Flip-flops','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'green'), 19.4),
 ('Flip-flops','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'yellow'), 19.4),
 ('Outdoor Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'red'), 24.6),
 ('Outdoor Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'blue'), 24.6),
 ('Outdoor Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'green'), 24.6),
 ('Outdoor Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'orange'), 24.6),
 ('Winter Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'gray'), 20.9),
 ('Winter Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'pink'), 20.9),
 ('Winter Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'green'), 20.9),
 ('Winter Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'purple'), 20.9),
 ('Winter Slippers','women', (SELECT categoryID FROM category WHERE categoryName = 'slippers'), (SELECT colorID FROM color WHERE colorName = 'blue'), 20.9);